#!/usr/bin/env python3
# coding: utf-8

##################################################
# OriginalFileName: ShellAdder.py                #
#                                                #
# This file is a part of The ShellAdder Project. #
# https://github.com/XiaoshuDeXiaowo/ShellAdder  #
#                                                #
# Released under the MIT License.                #
# Copyright (C) 2026 XiaoshuDeXiaowo.            #
##################################################

"""A tool to "pack" files into a Python script."""

__author__ = 'XiaoshuDeXiaowo'
__version__ = 'v0.0.2'
__all__ = ['__version__', 'run', 'main', 'zip_folder_contents', 'format_bytes']

import os
import shutil
import sys
from pathlib import Path
from tempfile import gettempdir
from zipfile import ZipFile, ZIP_DEFLATED, ZipInfo

_content = '''#!/usr/bin/env python3
# coding: utf-8

# Executable object code
#
# Created by: The ShellAdder Project %s
# https://github.com/XiaoshuDeXiaowo/ShellAdder
#
# WARNING: Any manual changes made to this file will be lost when ShellAdder
# is run again.  Do not edit this file unless you know what you are doing.

import os
import sys
import subprocess
import shutil
from tempfile import gettempdir
from zipfile import ZipFile

executable_bin = %s

tmpfile = os.path.join(gettempdir(), '%s')
with open(tmpfile, 'wb') as f:
    f.write(executable_bin)
tmpfolder = os.path.join(gettempdir(), '%s')
with ZipFile(tmpfile, 'r') as zipf:
    zipf.extractall(tmpfolder)
os.remove(tmpfile)
subprocess.run([%sos.path.join(tmpfolder, '%s')])
shutil.rmtree(tmpfolder)
'''

def format_bytes(data: bytes, bytes_per_line: int = 16) -> str:
    """ 将 bytes 对象转换为多行字节串字面量。

    Parameters
    ----------
    data: bytes
        原始二进制数据
    bytes_per_line: int = 16
        每行显示的字节数，默认 16

    Return
    ------
    data: str
        可用于写入 Python 源文件的字符串，例如：
        b"\\x00\\x01\\x02...\\x0f\\\n\\x10\\x11..."
    """
    # 将每个字节转换为 \xhh 格式（小写十六进制）
    hex_bytes = [f"\\x{b:02x}" for b in data]

    lines = []
    for i in range(0, len(hex_bytes), bytes_per_line):
        chunk = "".join(hex_bytes[i:i + bytes_per_line])
        lines.append(chunk)

    # 拼接行：第一行前加 b" ，每行后加续行符（最后一行不加），最后加闭合引号
    content = 'b"' + '\\\n'.join(lines) + '"'
    return content

def zip_folder_contents(source_folder, output_zip):
    """压缩文件夹。
    将 source_folder 内的所有文件和子文件夹压缩到 output_zip，
    压缩包内不包含 source_folder 本身（即直接以文件夹内容为根）。
    """
    with ZipFile(output_zip, 'w', ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(source_folder):
            for file in files:
                file_path = os.path.join(root, file)
                # 计算相对于源文件夹的路径，作为压缩包内的路径
                arcname = os.path.relpath(file_path, start=source_folder)
                # 统一使用正斜杠，保证跨平台兼容性
                arcname = arcname.replace(os.sep, '/')
                zipf.write(file_path, arcname)

        # 如果需要保留空文件夹，可以额外添加目录条目（可选）
        for root, dirs, files in os.walk(source_folder):
            for dir in dirs:
                dir_path = os.path.join(root, dir)
                arcname = os.path.relpath(dir_path, start=source_folder) + '/'
                arcname = arcname.replace(os.sep, '/')
                # 创建空目录条目（需要设置外部属性以标记为目录）
                info = ZipInfo(arcname)
                info.external_attr = 0o40755 << 16  # 目录权限
                zipf.writestr(info, '')

def run(input_file_or_folder: str, output: str, executable_name: str, verbose: bool = False) -> None:
    assert isinstance(input_file_or_folder, str), 'input_file_or_folder must be a string.'
    assert isinstance(output, str), 'output must be a string.'
    assert isinstance(executable_name, str), 'executable_name must be a string.'
    assert isinstance(verbose, bool), 'verbose must be a boolean.'
    global _content, __version__
    if verbose:
        sys.stderr.write(f'ShellAdder {__version__} is running on {sys.platform} using Python {sys.version}.\n')
        sys.stderr.write(f'Command line arguments as list: {sys.argv}\n')
        sys.stderr.write('Copyright (C) 2026 XiaoshuDeXiaowo.\n')
        sys.stderr.write('https://github.com/XiaoshuDeXiaowo/ShellAdder\n')
        sys.stderr.write('------------------------------------------------------\n')
        sys.stderr.flush()

    assert os.path.exists(input_file_or_folder), 'The specified input file (or folder) does not exist.'
    input_path = Path(input_file_or_folder)
    assert input_path.is_dir() or input_file_or_folder.endswith('zip'), 'The specified input file must be a zip file.'
    if verbose:
        sys.stderr.write(f'ShellAdder: {input_path = }\n')
        sys.stderr.flush()

    tmp_folder = Path(gettempdir()) / 'ShellAdder_tmp'
    tmp_folder.mkdir(exist_ok=True)
    if verbose:
        sys.stderr.write(f'ShellAdder: {tmp_folder = }\n')
        sys.stderr.flush()

    exe_suffix = executable_name.split('.')[-1]
    is_py = 'py' in exe_suffix
    if verbose:
        sys.stderr.write(f'ShellAdder: {exe_suffix = }\n')
        sys.stderr.write(f'ShellAdder: {is_py = }\n')
        sys.stderr.flush()

    try:
        with open(output, 'w', encoding='utf-8') as file:
            if input_path.is_dir():
                if verbose:
                    sys.stderr.write('The input_path is a dir. Compressing to zip file...\n')
                    sys.stderr.flush()
                zip_name = (tmp_folder / f'{input_path.name}.zip').absolute()
                zip_folder_contents(input_path, zip_name)
                input_path = Path(zip_name)
                if verbose:
                    sys.stderr.write(f'Compression completed. Compressed file: {input_path}\n')
                    sys.stderr.flush()
            elif verbose:
                sys.stderr.write('The input_path is a zip file.\n')
                sys.stderr.flush()
            repr_file_content = format_bytes(open(input_path, 'rb').read())
            if verbose:
                sys.stderr.write(f'Starting to write to file {output} ...\n')
                sys.stderr.flush()
            file.write(_content % (__version__,
                                   repr_file_content,
                                   input_path.name,
                                   input_path.name[:-4],
                                   'sys.executable, ' if is_py else '',
                                   executable_name))
            if verbose:
                sys.stderr.write(f'The output file {output} was successfully written.\n')
                sys.stderr.flush()
    finally:
        shutil.rmtree(tmp_folder)

def main():
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('input_file_or_folder', help='The zip file or folder to be "packed"')
    parser.add_argument('output', help='The output Python filename')
    parser.add_argument('executable_name', help='The Python script or executable file to run')
    parser.add_argument('-V', '--version', action='version', version=__version__, help='Show the version number and exit')
    parser.add_argument('-v', '--verbose', action='store_true', help='Output more information')

    args = parser.parse_args()
    run(args.input_file_or_folder, args.output, args.executable_name, args.verbose)
    return 0

if __name__ == '__main__':
    sys.exit(main())
