#!/usr/bin/env python3
# coding: utf-8

#################################################
# OriginalFileName: ShellAdder.py
#
# This file is a part of The ShellAdder Project.
# https://github.com/XiaoshuDeXiaowo/ShellAdder
#
# Released under the MIT License.
# Copyright (C) 2026 XiaoshuDeXiaowo.
#################################################

"""一个为一些文件“加壳”成 Python 文件的工具。"""

__version__ = 'v0.0.1'

import os
import shutil
import sys
from pathlib import Path
from tempfile import gettempdir
from zipfile import ZipFile, ZIP_DEFLATED, ZipInfo

_content = '''#!/usr/bin/env python3
# coding: utf-8

# Executable object code
#
# Created by: The ShellAdder Project %s
# https://github.com/XiaoshuDeXiaowo/ShellAdder
#
# WARNING: Any manual changes made to this file will be lost when ShellAdder
# is run again.  Do not edit this file unless you know what you are doing.

import os
import sys
import subprocess
import shutil
from tempfile import gettempdir
from zipfile import ZipFile

executable_bin = %s

tmpfile = os.path.join(gettempdir(), '%s')
with open(tmpfile, 'wb') as f:
    f.write(executable_bin)
tmpfolder = os.path.join(gettempdir(), '%s')
with ZipFile(tmpfile, 'r') as zipf:
    zipf.extractall(tmpfolder)
subprocess.run([%sos.path.join(tmpfolder, '%s')])
os.remove(tmpfile)
shutil.rmtree(tmpfolder)
'''

def zip_folder_contents(source_folder, output_zip):
    """压缩文件夹。
    将 source_folder 内的所有文件和子文件夹压缩到 output_zip，
    压缩包内不包含 source_folder 本身（即直接以文件夹内容为根）。
    """
    with ZipFile(output_zip, 'w', ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(source_folder):
            for file in files:
                file_path = os.path.join(root, file)
                # 计算相对于源文件夹的路径，作为压缩包内的路径
                arcname = os.path.relpath(file_path, start=source_folder)
                # 统一使用正斜杠，保证跨平台兼容性
                arcname = arcname.replace(os.sep, '/')
                zipf.write(file_path, arcname)

        # 如果需要保留空文件夹，可以额外添加目录条目（可选）
        for root, dirs, files in os.walk(source_folder):
            for dir in dirs:
                dir_path = os.path.join(root, dir)
                arcname = os.path.relpath(dir_path, start=source_folder) + '/'
                arcname = arcname.replace(os.sep, '/')
                # 创建空目录条目（需要设置外部属性以标记为目录）
                info = ZipInfo(arcname)
                info.external_attr = 0o40755 << 16  # 目录权限
                zipf.writestr(info, '')

def run(input_file_or_folder: str, output: str, executable_name: str, verbose: bool = False) -> None:
    assert isinstance(input_file_or_folder, str), 'input_file_or_folder must be a string.'
    assert isinstance(output, str), 'output must be a string.'
    assert isinstance(executable_name, str), 'executable_name must be a string.'
    assert isinstance(verbose, bool), 'verbose must be a boolean.'
    global _content, __version__
    if verbose:
        sys.stderr.write(f'ShellAdder {__version__} is running on {sys.platform} using Python {sys.version}.')
        sys.stderr.write(f'Command line arguments as list: {sys.argv}')
        sys.stderr.write('Copyright (C) 2026 XiaoshuDeXiaowo.')
        sys.stderr.write('https://github.com/XiaoshuDeXiaowo/ShellAdder')
        sys.stderr.flush()

    assert os.path.exists(input_file_or_folder), 'The specified input file does not exist.'
    input_path = Path(input_file_or_folder)
    if verbose:
        sys.stderr.write(f'ShellAdder: {input_path = }')
        sys.stderr.flush()

    tmp_folder = Path(gettempdir()) / 'ShellAdder.tmp'
    tmp_folder.mkdir(exist_ok=True)
    if verbose:
        sys.stderr.write(f'ShellAdder: {tmp_folder = }')
        sys.stderr.flush()

    exe_suffix = executable_name.split('.')[-1]
    is_py = 'py' in exe_suffix
    if verbose:
        sys.stderr.write(f'ShellAdder: {exe_suffix = }')
        sys.stderr.write(f'ShellAdder: {is_py = }')
        sys.stderr.flush()

    with open(output, 'w', encoding='utf-8') as file:
        if input_path.is_dir():
            zip_name = (tmp_folder / f'{input_path.name}.zip').absolute()
            zip_folder_contents(input_path, zip_name)
            input_path = Path(zip_name)
        repr_file_content = repr(open(input_path, 'rb').read())
        file.write(_content % (__version__,
                               repr_file_content,
                               input_path.name,
                               input_path.name,
                               'sys.executable, ' if is_py else '',
                               executable_name))
    shutil.rmtree(tmp_folder)

def main():
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('input_file_or_folder', help='要“加壳”的 zip 文件或文件夹')
    parser.add_argument('output', help='输出的 Python 文件名')
    parser.add_argument('executable_name', help='要执行的 Python 文件或可执行文件名')
    parser.add_argument('-V', '--version', action='version', version=__version__, help='显示版本号并退出')
    parser.add_argument('-v', '--verbose', action='store_true', help='输出更多信息')

    args = parser.parse_args()
    run(args.input_file_or_folder, args.output, args.executable_name, args.verbose)
    return 0

if __name__ == '__main__':
    sys.exit(main())
